### PR TITLE
snap: set proper desktop file name for the window

### PR DESCRIPTION
**Pull request by soumyaDghosh**

### CODE REVIEW

**Review by kenvandine — CHANGES_REQUESTED** [review]
Why comment out the cleanup and libraries parts? We want to keep it as lean as possible.

**Comment by soumyaDghosh** [comment]
> Why comment out the cleanup and libraries parts? We want to keep it as lean as possible.

I am testing my local build, and I think we don't need those libraries anymore. I tested in Kubuntu 24.10 in both Xorg and Wayland. That's why I commented out incase we need it. But, if you want to test it without keeping the comments we can do that too.

**Comment by kenvandine** [comment]
@soumyaDghosh if you're sure we don't need the libraries part please go ahead and remove that. Also, please uncomment the cleanup part.

**Comment by soumyaDghosh** [comment]
sorry, accidentally closed this while rebasing.

**Pull request closed without merging**
